name: CI Build (Self-Hosted)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  angular-test:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Angular dependencies
        working-directory: ./angular-app
        run: npm install

      - name: Run Angular tests
        working-directory: ./angular-app
        run: |
          npx ng test --watch=false --browsers=ChromeHeadless

  
  express-test:
    runs-on: self-hosted
    needs: angular-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Express dependencies
        working-directory: ./express-api
        run: npm install

      - name: Run Express tests
        working-directory: ./express-api
        run: npm test

  build-and-deploy:
    runs-on: self-hosted
    needs: [angular-test, express-test]

    steps:
      - name: Write SSH key
        run: |
          # Hardcode the BEGIN/END lines and inject the secret content in between
          $keyContent = "${{ secrets.EC2_SSH_KEY }}"
          $key = @"
          -----BEGIN RSA PRIVATE KEY-----
          $keyContent
          -----END RSA PRIVATE KEY-----
          "@
      
          $keyPath = "$env:RUNNER_WORKSPACE\temp_key.pem"
          [System.IO.File]::WriteAllText($keyPath, $key)
        
      - name: Checkout code
        uses: actions/checkout@v4

      # Express Api Updates
      - name: Copy Express API to EC2
        run: |
          $keyPath = "$env:RUNNER_WORKSPACE\temp_key.pem"
          scp -i $keyPath -o StrictHostKeyChecking=no -r ./express-api ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/

      - name: Restart Express API via PM2
        run: |
          $keyPath = "$env:RUNNER_WORKSPACE\temp_key.pem"
          $remoteCommand = @"
            cd /home/ec2-user/express-api &&
            npm install &&
            pm2 delete express-api || echo 'Not running' &&
            pm2 start server.js --name 'express-api' &&
            pm2 save
          "@
          $remoteCommand = [System.Text.RegularExpressions.Regex]::Replace($remoteCommand, "`r", "")
          ssh -i $keyPath -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "$remoteCommand"

      # Angular App Updates
      - name: Install Angular dependencies
        working-directory: ./angular-app
        run: npm install

      - name: Run Angular build script
        working-directory: ./angular-app
        run: npx ng build --configuration=production

      - name: Copy angular build file to EC2 host machine
        run: |
          $keyPath = "$env:RUNNER_WORKSPACE\temp_key.pem"
          scp -i $keyPath -o StrictHostKeyChecking=no -r ./angular-app/dist/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user
