name: CI Build (Self-Hosted)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      
      - name: Copy angular build file to EC2 host machine
        run: |
          $keyPath = "$env:RUNNER_WORKSPACE\temp_key.pem"
          scp -i $keyPath -o StrictHostKeyChecking=no -r ./dist/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user
          
      - name: Write SSH key
        run: |
          # Hardcode the BEGIN/END lines and inject the secret content in between
          $keyContent = "${{ secrets.EC2_SSH_KEY }}"
          $key = @"
          -----BEGIN RSA PRIVATE KEY-----
          $keyContent
          -----END RSA PRIVATE KEY-----
          "@
      
          $keyPath = "$env:RUNNER_WORKSPACE\temp_key.pem"
          [System.IO.File]::WriteAllText($keyPath, $key)
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: npx ng build --configuration=production

      - name: Copy angular build file to EC2 host machine
        run: |
          $keyPath = "$env:RUNNER_WORKSPACE\temp_key.pem"
          scp -i $keyPath -o StrictHostKeyChecking=no -r ./dist/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user
        
