name: CI Build (Self-Hosted)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Create private key file
        run: |
          $tempPath = Join-Path $env:RUNNER_TEMP "deploy_key.pem"
          @'
          ${{ secrets.EC2_SSH_KEY }}
          '@ > $tempPath

      - name: Grant permission to key file
        run: chmod 600 ./deploy_key.pem
        
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: npx ng build --configuration=production

      - name: Copy angular build file to EC2 host machine
        run: |
          $tempPath = Join-Path $env:RUNNER_TEMP "deploy_key.pem"
          scp -i $tempPath -o StrictHostKeyChecking=no -r ./dist/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/afluxgen/
        
