name: CI Build (Self-Hosted)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cache npm modules to speed up builds
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Bypass PowerShell execution policy
        run: powershell -Command "Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force"

      - name: Install dependencies
        run: npm install

      - name: Run build script
        run: ng build --configuration=production

      - name: Create private key file from repo secret
        run: echo ${{ secrets.EC2_SSH_KEY }} > ./deploy_key.pem

      - name: Grant permission to key file
        run: chmod 600 ./deploy_key.pem

      - name: Copy angular build file to EC2 host machine
        run: scp -i ./deploy_key.pem -o StrictHostKeyChecking=no -r ./dist/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/afluxgen/
        
